### ISSUE TITLE
stix-shifter interface does not use options in profile for translation

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#230]
**Describe the bug**
For the following profile:
```
profiles:
    host102:
        connector: mysql
        connection:
            host: 1.1.1.1
            port: 8888
            options:
                table: xxx
        config:
            auth:
                SEC: 123e4567-e89b-12d3-a456-426614174000
```

The information of `table: xxx` is never passed to translation, which will cause a stix-shifter error.

**Details of the bug**
Current implementation of the interface ignore the options, just
```
            dsl = translation.translate(
                connector_name, "query", query_metadata, pattern, {}
            )
```
Which should be
```
            dsl = translation.translate(
                connector_name, "query", query_metadata, pattern, options_from_profile
            )
```
